apiVersion: v1
kind: Service
metadata:
  name: {{ include "retroarch.fullname" . }}
  labels:
    {{- include "retroarch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: vnc
      protocol: TCP
      name: vnc
  selector:
    {{- include "retroarch.selectorLabels" . | nindent 4 }}
